erDiagram
    DIM_CUSTOMER ||--o{ FACT_OPERATIONS : customer_key
    DIM_ACCOUNT ||--o{ FACT_OPERATIONS : account_key
    DIM_PRODUCT ||--o{ FACT_OPERATIONS : product_key
    DIM_DATE ||--o{ FACT_OPERATIONS : date_key
    DIM_CARD ||--o{ FACT_OPERATIONS : card_key
    DIM_BRANCH ||--o{ FACT_OPERATIONS : branch_key
